blank_issues_enabled: false
contact_links:
  - name: FMP Official Support
    url: https://site.financialmodelingprep.com/developer/docs/stable
    about: For issues with the underlying FMP API service, contact FMP directly.
