// Financial statement types for FMP API
//
// Schema-first: Zod schemas are the source of truth; TypeScript types are
// derived via `z.infer`. Base schemas generated via `gen:schemas`.

import { z } from 'zod';

// Income Statement
export const IncomeStatementSchema = z.object({
  date: z.string(),
  symbol: z.string(),
  reportedCurrency: z.string(),
  cik: z.string(),
  filingDate: z.string(),
  acceptedDate: z.string(),
  fiscalYear: z.string(),
  period: z.string(),
  revenue: z.number(),
  costOfRevenue: z.number(),
  grossProfit: z.number(),
  researchAndDevelopmentExpenses: z.number(),
  generalAndAdministrativeExpenses: z.number(),
  sellingAndMarketingExpenses: z.number(),
  sellingGeneralAndAdministrativeExpenses: z.number(),
  otherExpenses: z.number(),
  operatingExpenses: z.number(),
  costAndExpenses: z.number(),
  netInterestIncome: z.number(),
  interestIncome: z.number(),
  interestExpense: z.number(),
  depreciationAndAmortization: z.number(),
  ebitda: z.number(),
  ebit: z.number(),
  nonOperatingIncomeExcludingInterest: z.number(),
  operatingIncome: z.number(),
  totalOtherIncomeExpensesNet: z.number(),
  incomeBeforeTax: z.number(),
  incomeTaxExpense: z.number(),
  netIncomeFromContinuingOperations: z.number(),
  netIncomeFromDiscontinuedOperations: z.number(),
  otherAdjustmentsToNetIncome: z.number(),
  netIncome: z.number(),
  netIncomeDeductions: z.number(),
  bottomLineNetIncome: z.number(),
  eps: z.number(),
  epsDiluted: z.number(),
  weightedAverageShsOut: z.number(),
  weightedAverageShsOutDil: z.number(),
});

export type IncomeStatement = z.infer<typeof IncomeStatementSchema>;

// Balance Sheet
export const BalanceSheetSchema = z.object({
  date: z.string(),
  symbol: z.string(),
  reportedCurrency: z.string(),
  cik: z.string(),
  filingDate: z.string(),
  acceptedDate: z.string(),
  fiscalYear: z.string(),
  period: z.string(),
  cashAndCashEquivalents: z.number(),
  shortTermInvestments: z.number(),
  cashAndShortTermInvestments: z.number(),
  netReceivables: z.number(),
  accountsReceivables: z.number(),
  otherReceivables: z.number(),
  inventory: z.number(),
  prepaids: z.number(),
  otherCurrentAssets: z.number(),
  totalCurrentAssets: z.number(),
  propertyPlantEquipmentNet: z.number(),
  goodwill: z.number(),
  intangibleAssets: z.number(),
  goodwillAndIntangibleAssets: z.number(),
  longTermInvestments: z.number(),
  taxAssets: z.number(),
  otherNonCurrentAssets: z.number(),
  totalNonCurrentAssets: z.number(),
  otherAssets: z.number(),
  totalAssets: z.number(),
  totalPayables: z.number(),
  accountPayables: z.number(),
  otherPayables: z.number(),
  accruedExpenses: z.number(),
  shortTermDebt: z.number(),
  capitalLeaseObligationsCurrent: z.number(),
  taxPayables: z.number(),
  deferredRevenue: z.number(),
  otherCurrentLiabilities: z.number(),
  totalCurrentLiabilities: z.number(),
  longTermDebt: z.number(),
  deferredRevenueNonCurrent: z.number(),
  deferredTaxLiabilitiesNonCurrent: z.number(),
  capitalLeaseObligationsNonCurrent: z.number(),
  otherNonCurrentLiabilities: z.number(),
  totalNonCurrentLiabilities: z.number(),
  otherLiabilities: z.number(),
  capitalLeaseObligations: z.number(),
  totalLiabilities: z.number(),
  treasuryStock: z.number(),
  preferredStock: z.number(),
  commonStock: z.number(),
  retainedEarnings: z.number(),
  additionalPaidInCapital: z.number(),
  accumulatedOtherComprehensiveIncomeLoss: z.number(),
  otherTotalStockholdersEquity: z.number(),
  totalStockholdersEquity: z.number(),
  totalEquity: z.number(),
  minorityInterest: z.number(),
  totalLiabilitiesAndTotalEquity: z.number(),
  totalInvestments: z.number(),
  totalDebt: z.number(),
  netDebt: z.number(),
});

export type BalanceSheet = z.infer<typeof BalanceSheetSchema>;

// Cash Flow Statement
export const CashFlowStatementSchema = z.object({
  date: z.string(),
  symbol: z.string(),
  reportedCurrency: z.string(),
  cik: z.string(),
  filingDate: z.string(),
  acceptedDate: z.string(),
  fiscalYear: z.string(),
  period: z.string(),
  netIncome: z.number(),
  depreciationAndAmortization: z.number(),
  deferredIncomeTax: z.number(),
  stockBasedCompensation: z.number(),
  changeInWorkingCapital: z.number(),
  accountsReceivables: z.number(),
  inventory: z.number(),
  accountsPayables: z.number(),
  otherWorkingCapital: z.number(),
  otherNonCashItems: z.number(),
  netCashProvidedByOperatingActivities: z.number(),
  investmentsInPropertyPlantAndEquipment: z.number(),
  acquisitionsNet: z.number(),
  purchasesOfInvestments: z.number(),
  salesMaturitiesOfInvestments: z.number(),
  otherInvestingActivities: z.number(),
  netCashProvidedByInvestingActivities: z.number(),
  netDebtIssuance: z.number(),
  longTermNetDebtIssuance: z.number(),
  shortTermNetDebtIssuance: z.number(),
  netStockIssuance: z.number(),
  netCommonStockIssuance: z.number(),
  commonStockIssuance: z.number(),
  commonStockRepurchased: z.number(),
  netPreferredStockIssuance: z.number(),
  netDividendsPaid: z.number(),
  commonDividendsPaid: z.number(),
  preferredDividendsPaid: z.number(),
  otherFinancingActivities: z.number(),
  netCashProvidedByFinancingActivities: z.number(),
  effectOfForexChangesOnCash: z.number(),
  netChangeInCash: z.number(),
  cashAtEndOfPeriod: z.number(),
  cashAtBeginningOfPeriod: z.number(),
  operatingCashFlow: z.number(),
  capitalExpenditure: z.number(),
  freeCashFlow: z.number(),
  incomeTaxesPaid: z.number(),
  interestPaid: z.number(),
});

export type CashFlowStatement = z.infer<typeof CashFlowStatementSchema>;

// Key Metrics
export const KeyMetricsSchema = z.object({
  symbol: z.string(),
  date: z.string(),
  fiscalYear: z.string(),
  period: z.string(),
  reportedCurrency: z.string(),
  marketCap: z.number(),
  enterpriseValue: z.number(),
  evToSales: z.number(),
  evToOperatingCashFlow: z.number(),
  evToFreeCashFlow: z.number(),
  evToEBITDA: z.number(),
  netDebtToEBITDA: z.number(),
  currentRatio: z.number(),
  incomeQuality: z.number(),
  grahamNumber: z.number(),
  grahamNetNet: z.number(),
  taxBurden: z.number(),
  interestBurden: z.number(),
  workingCapital: z.number(),
  investedCapital: z.number(),
  returnOnAssets: z.number(),
  operatingReturnOnAssets: z.number(),
  returnOnTangibleAssets: z.number(),
  returnOnEquity: z.number(),
  returnOnInvestedCapital: z.number(),
  returnOnCapitalEmployed: z.number(),
  earningsYield: z.number(),
  freeCashFlowYield: z.number(),
  capexToOperatingCashFlow: z.number(),
  capexToDepreciation: z.number(),
  capexToRevenue: z.number(),
  salesGeneralAndAdministrativeToRevenue: z.number(),
  researchAndDevelopementToRevenue: z.number(),
  stockBasedCompensationToRevenue: z.number(),
  intangiblesToTotalAssets: z.number(),
  averageReceivables: z.number(),
  averagePayables: z.number(),
  averageInventory: z.number(),
  daysOfSalesOutstanding: z.number(),
  daysOfPayablesOutstanding: z.number(),
  daysOfInventoryOutstanding: z.number(),
  operatingCycle: z.number(),
  cashConversionCycle: z.number(),
  freeCashFlowToEquity: z.number(),
  freeCashFlowToFirm: z.number(),
  tangibleAssetValue: z.number(),
  netCurrentAssetValue: z.number(),
});

export type KeyMetrics = z.infer<typeof KeyMetricsSchema>;

// Financial Ratios
export const FinancialRatiosSchema = z.object({
  symbol: z.string(),
  date: z.string(),
  fiscalYear: z.string(),
  period: z.string(),
  reportedCurrency: z.string(),
  grossProfitMargin: z.number(),
  ebitMargin: z.number(),
  ebitdaMargin: z.number(),
  operatingProfitMargin: z.number(),
  pretaxProfitMargin: z.number(),
  continuousOperationsProfitMargin: z.number(),
  netProfitMargin: z.number(),
  bottomLineProfitMargin: z.number(),
  receivablesTurnover: z.number(),
  payablesTurnover: z.number(),
  inventoryTurnover: z.number(),
  fixedAssetTurnover: z.number(),
  assetTurnover: z.number(),
  currentRatio: z.number(),
  quickRatio: z.number(),
  solvencyRatio: z.number(),
  cashRatio: z.number(),
  priceToEarningsRatio: z.number(),
  priceToEarningsGrowthRatio: z.number(),
  forwardPriceToEarningsGrowthRatio: z.number(),
  priceToBookRatio: z.number(),
  priceToSalesRatio: z.number(),
  priceToFreeCashFlowRatio: z.number(),
  priceToOperatingCashFlowRatio: z.number(),
  debtToAssetsRatio: z.number(),
  debtToEquityRatio: z.number(),
  debtToCapitalRatio: z.number(),
  longTermDebtToCapitalRatio: z.number(),
  financialLeverageRatio: z.number(),
  workingCapitalTurnoverRatio: z.number(),
  operatingCashFlowRatio: z.number(),
  operatingCashFlowSalesRatio: z.number(),
  freeCashFlowOperatingCashFlowRatio: z.number(),
  debtServiceCoverageRatio: z.number(),
  interestCoverageRatio: z.number(),
  shortTermOperatingCashFlowCoverageRatio: z.number(),
  operatingCashFlowCoverageRatio: z.number(),
  capitalExpenditureCoverageRatio: z.number(),
  dividendPaidAndCapexCoverageRatio: z.number(),
  dividendPayoutRatio: z.number(),
  dividendYield: z.number(),
  dividendYieldPercentage: z.number(),
  dividendPerShare: z.number(),
  revenuePerShare: z.number(),
  netIncomePerShare: z.number(),
  interestDebtPerShare: z.number(),
  cashPerShare: z.number(),
  bookValuePerShare: z.number(),
  tangibleBookValuePerShare: z.number(),
  shareholdersEquityPerShare: z.number(),
  operatingCashFlowPerShare: z.number(),
  capexPerShare: z.number(),
  freeCashFlowPerShare: z.number(),
  netIncomePerEBT: z.number(),
  ebtPerEbit: z.number(),
  priceToFairValue: z.number(),
  debtToMarketCap: z.number(),
  effectiveTaxRate: z.number(),
  enterpriseValueMultiple: z.number(),
});

export type FinancialRatios = z.infer<typeof FinancialRatiosSchema>;

// Enterprise Value
export const EnterpriseValueSchema = z.object({
  symbol: z.string(),
  date: z.string(),
  stockPrice: z.number(),
  numberOfShares: z.number(),
  marketCapitalization: z.number(),
  minusCashAndCashEquivalents: z.number(),
  addTotalDebt: z.number(),
  enterpriseValue: z.number(),
});

export type EnterpriseValue = z.infer<typeof EnterpriseValueSchema>;

// Cashflow Growth
export const CashflowGrowthSchema = z.object({
  symbol: z.string(),
  date: z.string(),
  fiscalYear: z.string(),
  period: z.string(),
  reportedCurrency: z.string(),
  growthNetIncome: z.number(),
  growthDepreciationAndAmortization: z.number(),
  growthDeferredIncomeTax: z.number(),
  growthStockBasedCompensation: z.number(),
  growthChangeInWorkingCapital: z.number(),
  growthAccountsReceivables: z.number(),
  growthInventory: z.number(),
  growthAccountsPayables: z.number(),
  growthOtherWorkingCapital: z.number(),
  growthOtherNonCashItems: z.number(),
  growthNetCashProvidedByOperatingActivites: z.number(),
  growthInvestmentsInPropertyPlantAndEquipment: z.number(),
  growthAcquisitionsNet: z.number(),
  growthPurchasesOfInvestments: z.number(),
  growthSalesMaturitiesOfInvestments: z.number(),
  growthOtherInvestingActivites: z.number(),
  growthNetCashUsedForInvestingActivites: z.number(),
  growthDebtRepayment: z.number(),
  growthCommonStockIssued: z.number(),
  growthCommonStockRepurchased: z.number(),
  growthDividendsPaid: z.number(),
  growthOtherFinancingActivites: z.number(),
  growthNetCashUsedProvidedByFinancingActivities: z.number(),
  growthEffectOfForexChangesOnCash: z.number(),
  growthNetChangeInCash: z.number(),
  growthCashAtEndOfPeriod: z.number(),
  growthCashAtBeginningOfPeriod: z.number(),
  growthOperatingCashFlow: z.number(),
  growthCapitalExpenditure: z.number(),
  growthFreeCashFlow: z.number(),
  growthNetDebtIssuance: z.number(),
  growthLongTermNetDebtIssuance: z.number(),
  growthShortTermNetDebtIssuance: z.number(),
  growthNetStockIssuance: z.number(),
  growthPreferredDividendsPaid: z.number(),
  growthIncomeTaxesPaid: z.number(),
  growthInterestPaid: z.number(),
});

export type CashflowGrowth = z.infer<typeof CashflowGrowthSchema>;

// Income Growth
export const IncomeGrowthSchema = z.object({
  symbol: z.string(),
  date: z.string(),
  fiscalYear: z.string(),
  period: z.string(),
  reportedCurrency: z.string(),
  growthRevenue: z.number(),
  growthCostOfRevenue: z.number(),
  growthGrossProfit: z.number(),
  growthGrossProfitRatio: z.number(),
  growthResearchAndDevelopmentExpenses: z.number(),
  growthGeneralAndAdministrativeExpenses: z.number(),
  growthSellingAndMarketingExpenses: z.number(),
  growthOtherExpenses: z.number(),
  growthOperatingExpenses: z.number(),
  growthCostAndExpenses: z.number(),
  growthInterestIncome: z.number(),
  growthInterestExpense: z.number(),
  growthDepreciationAndAmortization: z.number(),
  growthEBITDA: z.number(),
  growthOperatingIncome: z.number(),
  growthIncomeBeforeTax: z.number(),
  growthIncomeTaxExpense: z.number(),
  growthNetIncome: z.number(),
  growthEPS: z.number(),
  growthEPSDiluted: z.number(),
  growthWeightedAverageShsOut: z.number(),
  growthWeightedAverageShsOutDil: z.number(),
  growthEBIT: z.number(),
  growthNonOperatingIncomeExcludingInterest: z.number(),
  growthNetInterestIncome: z.number(),
  growthTotalOtherIncomeExpensesNet: z.number(),
  growthNetIncomeFromContinuingOperations: z.number(),
  growthOtherAdjustmentsToNetIncome: z.number(),
  growthNetIncomeDeductions: z.number(),
});

export type IncomeGrowth = z.infer<typeof IncomeGrowthSchema>;

// Balance Sheet Growth
export const BalanceSheetGrowthSchema = z.object({
  symbol: z.string(),
  date: z.string(),
  fiscalYear: z.string(),
  period: z.string(),
  reportedCurrency: z.string(),
  growthCashAndCashEquivalents: z.number(),
  growthShortTermInvestments: z.number(),
  growthCashAndShortTermInvestments: z.number(),
  growthNetReceivables: z.number(),
  growthInventory: z.number(),
  growthOtherCurrentAssets: z.number(),
  growthTotalCurrentAssets: z.number(),
  growthPropertyPlantEquipmentNet: z.number(),
  growthGoodwill: z.number(),
  growthIntangibleAssets: z.number(),
  growthGoodwillAndIntangibleAssets: z.number(),
  growthLongTermInvestments: z.number(),
  growthTaxAssets: z.number(),
  growthOtherNonCurrentAssets: z.number(),
  growthTotalNonCurrentAssets: z.number(),
  growthOtherAssets: z.number(),
  growthTotalAssets: z.number(),
  growthAccountPayables: z.number(),
  growthShortTermDebt: z.number(),
  growthTaxPayables: z.number(),
  growthDeferredRevenue: z.number(),
  growthOtherCurrentLiabilities: z.number(),
  growthTotalCurrentLiabilities: z.number(),
  growthLongTermDebt: z.number(),
  growthDeferredRevenueNonCurrent: z.number(),
  growthDeferredTaxLiabilitiesNonCurrent: z.number(),
  growthOtherNonCurrentLiabilities: z.number(),
  growthTotalNonCurrentLiabilities: z.number(),
  growthOtherLiabilities: z.number(),
  growthTotalLiabilities: z.number(),
  growthPreferredStock: z.number(),
  growthCommonStock: z.number(),
  growthRetainedEarnings: z.number(),
  growthAccumulatedOtherComprehensiveIncomeLoss: z.number(),
  growthOthertotalStockholdersEquity: z.number(),
  growthTotalStockholdersEquity: z.number(),
  growthMinorityInterest: z.number(),
  growthTotalEquity: z.number(),
  growthTotalLiabilitiesAndStockholdersEquity: z.number(),
  growthTotalInvestments: z.number(),
  growthTotalDebt: z.number(),
  growthNetDebt: z.number(),
  growthAccountsReceivables: z.number(),
  growthOtherReceivables: z.number(),
  growthPrepaids: z.number(),
  growthTotalPayables: z.number(),
  growthOtherPayables: z.number(),
  growthAccruedExpenses: z.number(),
  growthCapitalLeaseObligationsCurrent: z.number(),
  growthAdditionalPaidInCapital: z.number(),
  growthTreasuryStock: z.number(),
});

export type BalanceSheetGrowth = z.infer<typeof BalanceSheetGrowthSchema>;

// Financial Growth
export const FinancialGrowthSchema = z.object({
  symbol: z.string(),
  date: z.string(),
  fiscalYear: z.string(),
  period: z.string(),
  reportedCurrency: z.string(),
  revenueGrowth: z.number(),
  grossProfitGrowth: z.number(),
  ebitgrowth: z.number(),
  operatingIncomeGrowth: z.number(),
  netIncomeGrowth: z.number(),
  epsgrowth: z.number(),
  epsdilutedGrowth: z.number(),
  weightedAverageSharesGrowth: z.number(),
  weightedAverageSharesDilutedGrowth: z.number(),
  dividendsPerShareGrowth: z.number(),
  operatingCashFlowGrowth: z.number(),
  receivablesGrowth: z.number(),
  inventoryGrowth: z.number(),
  assetGrowth: z.number(),
  bookValueperShareGrowth: z.number(),
  debtGrowth: z.number(),
  rdexpenseGrowth: z.number(),
  sgaexpensesGrowth: z.number(),
  freeCashFlowGrowth: z.number(),
  tenYRevenueGrowthPerShare: z.number(),
  fiveYRevenueGrowthPerShare: z.number(),
  threeYRevenueGrowthPerShare: z.number(),
  tenYOperatingCFGrowthPerShare: z.number(),
  fiveYOperatingCFGrowthPerShare: z.number(),
  threeYOperatingCFGrowthPerShare: z.number(),
  tenYNetIncomeGrowthPerShare: z.number(),
  fiveYNetIncomeGrowthPerShare: z.number(),
  threeYNetIncomeGrowthPerShare: z.number(),
  tenYShareholdersEquityGrowthPerShare: z.number(),
  fiveYShareholdersEquityGrowthPerShare: z.number(),
  threeYShareholdersEquityGrowthPerShare: z.number(),
  tenYDividendperShareGrowthPerShare: z.number(),
  fiveYDividendperShareGrowthPerShare: z.number(),
  threeYDividendperShareGrowthPerShare: z.number(),
  ebitdaGrowth: z.number(),
  growthCapitalExpenditure: z.number(),
  tenYBottomLineNetIncomeGrowthPerShare: z.number(),
  fiveYBottomLineNetIncomeGrowthPerShare: z.number(),
  threeYBottomLineNetIncomeGrowthPerShare: z.number(),
});

export type FinancialGrowth = z.infer<typeof FinancialGrowthSchema>;

// Earnings Historical
export const EarningsHistoricalSchema = z.object({
  date: z.string(),
  symbol: z.string(),
  // Actuals are null for earnings that haven't been reported yet.
  epsActual: z.number().nullable(),
  epsEstimated: z.number().nullable(),
  revenueActual: z.number().nullable(),
  revenueEstimated: z.number().nullable(),
  lastUpdated: z.string(),
});

export type EarningsHistorical = z.infer<typeof EarningsHistoricalSchema>;

// Earnings Surprises
export const EarningsSurprisesSchema = z.object({
  date: z.string(),
  symbol: z.string(),
  actualEarningResult: z.number(),
  estimatedEarning: z.number(),
});

export type EarningsSurprises = z.infer<typeof EarningsSurprisesSchema>;

// Financial Scores (Altman Z-Score + Piotroski + components) — stable /financial-scores.
// Verified against the live FMP `stable` API (2026-05-27).
export const FinancialScoresSchema = z.object({
  symbol: z.string(),
  reportedCurrency: z.string().nullable(),
  altmanZScore: z.number(),
  piotroskiScore: z.number(),
  workingCapital: z.number(),
  totalAssets: z.number(),
  retainedEarnings: z.number(),
  ebit: z.number(),
  marketCap: z.number(),
  totalLiabilities: z.number(),
  revenue: z.number(),
});

export type FinancialScores = z.infer<typeof FinancialScoresSchema>;

// Key Metrics TTM (trailing-twelve-month snapshot) — stable /key-metrics-ttm.
// Verified against the live FMP `stable` API (2026-05-27).
export const KeyMetricsTTMSchema = z.object({
  symbol: z.string(),
  marketCap: z.number(),
  enterpriseValueTTM: z.number(),
  evToSalesTTM: z.number(),
  evToOperatingCashFlowTTM: z.number(),
  evToFreeCashFlowTTM: z.number(),
  evToEBITDATTM: z.number(),
  netDebtToEBITDATTM: z.number(),
  currentRatioTTM: z.number(),
  incomeQualityTTM: z.number(),
  grahamNumberTTM: z.number(),
  grahamNetNetTTM: z.number(),
  taxBurdenTTM: z.number(),
  interestBurdenTTM: z.number(),
  workingCapitalTTM: z.number(),
  investedCapitalTTM: z.number(),
  returnOnAssetsTTM: z.number(),
  operatingReturnOnAssetsTTM: z.number(),
  returnOnTangibleAssetsTTM: z.number(),
  returnOnEquityTTM: z.number(),
  returnOnInvestedCapitalTTM: z.number(),
  returnOnCapitalEmployedTTM: z.number(),
  earningsYieldTTM: z.number(),
  freeCashFlowYieldTTM: z.number(),
  capexToOperatingCashFlowTTM: z.number(),
  capexToDepreciationTTM: z.number(),
  capexToRevenueTTM: z.number(),
  salesGeneralAndAdministrativeToRevenueTTM: z.number(),
  researchAndDevelopementToRevenueTTM: z.number(),
  stockBasedCompensationToRevenueTTM: z.number(),
  intangiblesToTotalAssetsTTM: z.number(),
  averageReceivablesTTM: z.number(),
  averagePayablesTTM: z.number(),
  averageInventoryTTM: z.number(),
  daysOfSalesOutstandingTTM: z.number(),
  daysOfPayablesOutstandingTTM: z.number(),
  daysOfInventoryOutstandingTTM: z.number(),
  operatingCycleTTM: z.number(),
  cashConversionCycleTTM: z.number(),
  freeCashFlowToEquityTTM: z.number(),
  freeCashFlowToFirmTTM: z.number(),
  tangibleAssetValueTTM: z.number(),
  netCurrentAssetValueTTM: z.number(),
});

export type KeyMetricsTTM = z.infer<typeof KeyMetricsTTMSchema>;

// Financial Ratios TTM (trailing-twelve-month snapshot) — stable /ratios-ttm.
// Verified against the live FMP `stable` API (2026-05-27).
export const FinancialRatiosTTMSchema = z.object({
  symbol: z.string(),
  grossProfitMarginTTM: z.number(),
  ebitMarginTTM: z.number(),
  ebitdaMarginTTM: z.number(),
  operatingProfitMarginTTM: z.number(),
  pretaxProfitMarginTTM: z.number(),
  continuousOperationsProfitMarginTTM: z.number(),
  netProfitMarginTTM: z.number(),
  bottomLineProfitMarginTTM: z.number(),
  receivablesTurnoverTTM: z.number(),
  payablesTurnoverTTM: z.number(),
  inventoryTurnoverTTM: z.number(),
  fixedAssetTurnoverTTM: z.number(),
  assetTurnoverTTM: z.number(),
  currentRatioTTM: z.number(),
  quickRatioTTM: z.number(),
  solvencyRatioTTM: z.number(),
  cashRatioTTM: z.number(),
  priceToEarningsRatioTTM: z.number(),
  priceToEarningsGrowthRatioTTM: z.number(),
  forwardPriceToEarningsGrowthRatioTTM: z.number(),
  priceToBookRatioTTM: z.number(),
  priceToSalesRatioTTM: z.number(),
  priceToFreeCashFlowRatioTTM: z.number(),
  priceToOperatingCashFlowRatioTTM: z.number(),
  debtToAssetsRatioTTM: z.number(),
  debtToEquityRatioTTM: z.number(),
  debtToCapitalRatioTTM: z.number(),
  longTermDebtToCapitalRatioTTM: z.number(),
  financialLeverageRatioTTM: z.number(),
  workingCapitalTurnoverRatioTTM: z.number(),
  operatingCashFlowRatioTTM: z.number(),
  operatingCashFlowSalesRatioTTM: z.number(),
  freeCashFlowOperatingCashFlowRatioTTM: z.number(),
  debtServiceCoverageRatioTTM: z.number(),
  interestCoverageRatioTTM: z.number(),
  shortTermOperatingCashFlowCoverageRatioTTM: z.number(),
  operatingCashFlowCoverageRatioTTM: z.number(),
  capitalExpenditureCoverageRatioTTM: z.number(),
  dividendPaidAndCapexCoverageRatioTTM: z.number(),
  dividendPayoutRatioTTM: z.number(),
  dividendYieldTTM: z.number(),
  enterpriseValueTTM: z.number(),
  revenuePerShareTTM: z.number(),
  netIncomePerShareTTM: z.number(),
  interestDebtPerShareTTM: z.number(),
  cashPerShareTTM: z.number(),
  bookValuePerShareTTM: z.number(),
  tangibleBookValuePerShareTTM: z.number(),
  shareholdersEquityPerShareTTM: z.number(),
  operatingCashFlowPerShareTTM: z.number(),
  capexPerShareTTM: z.number(),
  freeCashFlowPerShareTTM: z.number(),
  netIncomePerEBTTTM: z.number(),
  ebtPerEbitTTM: z.number(),
  priceToFairValueTTM: z.number(),
  debtToMarketCapTTM: z.number(),
  effectiveTaxRateTTM: z.number(),
  enterpriseValueMultipleTTM: z.number(),
  dividendPerShareTTM: z.number(),
});

export type FinancialRatiosTTM = z.infer<typeof FinancialRatiosTTMSchema>;

// Revenue segmentation (product & geographic share one shape) — stable
// /revenue-product-segmentation and /revenue-geographic-segmentation. The `data`
// object is keyed dynamically by product line / region.
// Verified against the live FMP `stable` API (2026-05-27).
export const RevenueSegmentationSchema = z.object({
  symbol: z.string(),
  fiscalYear: z.number(),
  period: z.string(),
  reportedCurrency: z.string().nullable(),
  date: z.string(),
  data: z.record(z.string(), z.number()),
});

export const RevenueProductSegmentationSchema = RevenueSegmentationSchema;
export const RevenueGeographicSegmentationSchema = RevenueSegmentationSchema;
export type RevenueProductSegmentation = z.infer<typeof RevenueSegmentationSchema>;
export type RevenueGeographicSegmentation = z.infer<typeof RevenueSegmentationSchema>;
